import catchAsync from '../utils/catchAsync.js';
import AppError from '../utils/AppError.js';
import AiService from '../services/AiService.js';
import AnalyticsService from '../services/AnalyticsService.js';
import OpenAI from 'openai';

// Initialize the OpenAI client lazily
let openaiClient = null;
const getOpenAIClient = () => {
  if (!openaiClient) {
    openaiClient = new OpenAI({ 
      apiKey: process.env.OPENAI_API_KEY || 'dummy_key' 
    });
  }
  return openaiClient;
};

/**
 * AI Powered Business Insights
 */
export const getBusinessInsights = catchAsync(async (req, res, next) => {
  // 1. Fetch data context using the AnalyticsService (Relational/Prisma)
  const dashboardData = await AnalyticsService.getDashboardData(req.user.id);

  // 2. Map context for the AI service
  const dataContext = {
    metrics: dashboardData.metrics,
    charts: {
      topProducts: dashboardData.charts.topProducts.slice(0, 3)
    }
  };

  // 3. Generate Insights via AI Service
  const insights = await AiService.generateBusinessInsights(dataContext);

  res.json({
    success: true,
    data: { insights }
  });
});

/**
 * Line Item Generation
 */
export const generateLineItems = catchAsync(async (req, res, next) => {
  const { prompt } = req.body;
  
  if (!prompt || typeof prompt !== 'string' || prompt.trim() === '') {
    return next(new AppError('A valid descriptive prompt is required.', 400));
  }

  const apiKey = process.env.OPENAI_API_KEY;
  // If no real API key, fallback to mock
  if (!apiKey || apiKey.startsWith('sk-proj-xxx') || apiKey === 'dummy_key') {
    return sendMockResponse(res, prompt);
  }

  try {
    const client = getOpenAIClient();
    
    const systemPrompt = `
      You are an expert accountant for "VyaparFlow".
      Break down the prompt into 1-4 professional invoice line items.
      OUTPUT FORMAT (JSON ONLY): 
      { 
        "items": [ { "description": "Professional item name", "qty": number, "rate": number } ], 
        "notes": "string", 
        "suggestedTax": number 
      }
    `;

    const response = await client.chat.completions.create({
      model: "gpt-4o-mini",
      response_format: { type: "json_object" },
      messages: [
        { role: "system", content: systemPrompt },
        { role: "user", content: `Generate an invoice for: ${prompt}` }
      ],
      timeout: 10000
    });

    const parsedData = JSON.parse(response.choices[0].message.content);
    
    res.json({
      success: true,
      data: {
        items: (parsedData.items || []).map((item, idx) => ({
          id: `ai_${Date.now()}_${idx}`,
          description: item.description || 'Service',
          qty: Number(item.qty) || 1,
          rate: Number(item.rate) || 0
        })),
        notes: parsedData.notes || 'Generated by AI.',
        suggestedTax: Number(parsedData.suggestedTax) || 0
      }
    });

  } catch (error) {
    console.error('OPENAI_GENERATE_ERROR:', error.message);
    return sendMockResponse(res, prompt, true);
  }
});

const sendMockResponse = (res, prompt, isError = false) => {
  res.json({
    success: true,
    data: {
      isMock: true,
      items: [
        { id: `mock_${Date.now()}_1`, description: `${prompt.substring(0, 30)}...`, qty: 1, rate: 850 },
      ],
      notes: isError ? "AI service busy." : "Demo Mode.",
      suggestedTax: 18
    }
  });
};
