import OpenAI from 'openai';

// Initialize the OpenAI client lazily to ensure environment variables are loaded
let openaiClient = null;
const getOpenAIClient = () => {
  if (!openaiClient) {
    openaiClient = new OpenAI({ 
      apiKey: process.env.OPENAI_API_KEY || 'dummy_key_to_prevent_crash_at_startup' 
    });
  }
  return openaiClient;
};

/**
 * Controller that translates raw string prompts into structured invoice line items.
 * Uses OpenAI for NLP interpretation and provides a robust mock fallback if the service fails.
 */
export const generateLineItems = async (req, res) => {
  const { prompt } = req.body;
  
  if (!prompt || typeof prompt !== 'string' || prompt.trim() === '') {
    return res.status(400).json({ success: false, error: 'A valid descriptive prompt is required.' });
  }

  // Check if API Key is configured before attempting the call
  const apiKey = process.env.OPENAI_API_KEY;
  if (!apiKey || apiKey.startsWith('sk-proj-xxx')) {
    console.warn('⚠️  OPENAI_API_KEY is missing or invalid. Falling back to Mock Generator.');
    return sendMockResponse(res, prompt);
  }

  try {
    const client = getOpenAIClient();
    
    const systemPrompt = `
      You are an expert accountant for "VyaparFlow", a professional invoice generation SaaS.
      The user will describe a job, project, or service. 
      Break this down into 1-4 highly realistic, professional line items.
      Ensure the quantities (qty) and rates are industry-standard for the described work.
      
      OUTPUT FORMAT (JSON ONLY): 
      { 
        "items": [ 
          { "description": "Professional item name", "qty": number, "rate": number } 
        ], 
        "notes": "A helpful, professional note about the service", 
        "suggestedTax": number (0-18)
      }
    `;

    const response = await client.chat.completions.create({
      model: "gpt-4o-mini",
      response_format: { type: "json_object" },
      messages: [
        { role: "system", content: systemPrompt },
        { role: "user", content: `Generate an invoice for: ${prompt}` }
      ],
      timeout: 10000 // 10 second timeout for responsiveness
    });

    const parsedData = JSON.parse(response.choices[0].message.content);
    
    res.json({
      success: true,
      items: (parsedData.items || []).map((item, idx) => ({
        id: `ai_${Date.now()}_${idx}`,
        description: item.description || 'Consultation Service',
        qty: Number(item.qty) || 1,
        rate: Number(item.rate) || 0
      })),
      notes: parsedData.notes || 'Generated by VyaparFlow AI. Thank you for your business.',
      suggestedTax: Number(parsedData.suggestedTax) || 0
    });

  } catch (error) {
    console.error('❌ OpenAI API Error:', error.message);
    return sendMockResponse(res, prompt, true);
  }
};

/**
 * Helper to send a consistent mock response when AI is unavailable or unconfigured.
 */
const sendMockResponse = (res, prompt, isError = false) => {
  res.json({
    success: true,
    isMock: true,
    items: [
      { id: `mock_${Date.now()}_1`, description: `${prompt.substring(0, 30)}... (Service)`, qty: 1, rate: 850 },
      { id: `mock_${Date.now()}_2`, description: 'Technical Consultation & Setup', qty: 2, rate: 125 },
    ],
    notes: isError 
      ? "AI service is currently busy. Here's a structured draft based on your prompt." 
      : "Demo Mode: Configure an OPENAI_API_KEY to enable full AI intelligence.",
    suggestedTax: 12
  });
};
